from __future__ import annotations

from typing import Any, Literal

from loguru import logger

from ...agents import qa_checker, report_generator
from .state import SynthesisState


async def run_qa_check(state: SynthesisState):
    try:
        result = await qa_checker.run_qa_check(
            patient_profile=state.get("patient_profile") or {},
            eligibility_verdicts=state.get("eligibility_verdicts") or {},
            scored_trials=state.get("trial_scores") or [],
        )
        qa_passed = result.get("qa_passed", True)
        issues = result.get("qa_issues", [])
        return {
            "qa_passed": qa_passed,
            "qa_issues": issues,
            "new_decision_entries": [
                f"QA check {'passed' if qa_passed else 'found issues'}: {len(issues)} issue(s)."
            ],
        }
    except Exception as exc:
        logger.error("run_qa_check failed: {}", exc)
        return {
            "qa_passed": True,
            "qa_issues": [f"QA check error (proceeding): {exc}"],
            "new_errors": [f"qa_check: {exc}"],
            "new_decision_entries": [f"QA check failed, proceeding anyway: {exc}"],
        }


def route_after_qa(
    state: SynthesisState,
) -> Literal["generate_report", "attempt_qa_fix", "flag_re_evaluation"]:
    """Route based on QA result and fix attempt count."""
    if state.get("qa_passed", True):
        return "generate_report"
    if state.get("qa_fix_attempts", 0) < 1:
        return "attempt_qa_fix"
    return "flag_re_evaluation"


async def attempt_qa_fix(state: SynthesisState):
    """Attempt to fix QA issues by re-sorting/re-scoring within synthesis."""
    issues = state.get("qa_issues") or []
    scored = list(state.get("trial_scores") or [])

    # Re-sort by score
    scored.sort(key=lambda x: x.get("score", 0), reverse=True)

    fix_attempts = state.get("qa_fix_attempts", 0)
    return {
        "trial_scores": scored,
        "qa_fix_attempts": fix_attempts + 1,
        "new_decision_entries": [
            f"QA fix attempt {fix_attempts + 1}: re-sorted trial rankings to resolve: {issues[:2]}"
        ],
    }


async def flag_re_evaluation(state: SynthesisState) -> dict[str, Any]:
    """Flag that the supervisor should re-run eligibility reasoning."""
    issues = state.get("qa_issues") or []
    return {
        "synthesis_needs_re_evaluation": True,
        "new_decision_entries": [
            f"Synthesis flagging re-evaluation needed due to persistent QA issues: {issues[:3]}"
        ],
    }


def _collect_synthesis_inputs(state: SynthesisState) -> dict[str, Any]:
    return {
        "patient_profile": state.get("patient_profile") or {},
        "scored_trials": state.get("trial_scores") or [],
        "missing_info": state.get("missing_info_recommendations") or [],
        "eligibility_verdicts": state.get("eligibility_verdicts") or {},
        "trials_raw": state.get("trials_raw") or [],
        "search_queries": state.get("search_queries") or [],
        "decision_history": (
            list(state.get("decision_history") or [])
            + list(state.get("new_decision_entries") or [])
        ),
        "qa_issues": state.get("qa_issues") or [],
    }


async def generate_report_node(state: SynthesisState) -> dict[str, Any]:
    """Generate the final report."""
    try:
        ctx = _collect_synthesis_inputs(state)
        report = await report_generator.build_report(**ctx)
        return {
            "report_json": report,
            "report_text": report_generator.build_text_report(report),
            "synthesis_needs_re_evaluation": False,
            "new_decision_entries": ["Final report generated by synthesis sub-agent."],
        }
    except Exception as exc:
        logger.error("generate_report failed: {}", exc)
        return {
            "report_json": {"error": str(exc)},
            "report_text": f"Report generation failed: {exc}",
            "synthesis_needs_re_evaluation": False,
            "new_errors": [f"generate_report: {exc}"],
            "new_decision_entries": [f"Report generation failed: {exc}"],
        }


async def finalize_synthesis_output(state: SynthesisState) -> dict[str, Any]:
    """Collect new_decision_entries and new_errors into output keys."""
    return {
        "qa_issues": list(state.get("qa_issues") or []),
        "qa_passed": bool(state.get("qa_passed", True)),
        "report_json": state.get("report_json"),
        "report_text": state.get("report_text"),
        "synthesis_needs_re_evaluation": bool(state.get("synthesis_needs_re_evaluation", False)),
        "decision_history": list(state.get("new_decision_entries") or []),
        "errors": list(state.get("new_errors") or []),
    }
