from typing import Literal

from agents import qa_checker, report_generator
from loguru import logger

from .qa_remediation import (
    attempt_qa_fix as _attempt_qa_fix_impl,
)
from .qa_remediation import (
    build_remediation_summary,
    collect_synthesis_inputs,
    normalize_qa_issues,
)
from .qa_remediation import (
    flag_re_evaluation as _flag_re_evaluation_impl,
)
from .state import SynthesisState

_MAX_QA_FIX_ATTEMPTS = 2


def _exception_label(exc: Exception) -> str:
    if isinstance(exc, TimeoutError):
        return "timeout"
    return exc.__class__.__name__


async def run_qa_check(state: SynthesisState) -> dict[str, object]:
    try:
        result = await qa_checker.run_qa_check(
            patient_profile=state.get("patient_profile") or {},
            eligibility_verdicts=state.get("eligibility_verdicts") or {},
            scored_trials=state.get("trial_scores") or [],
            retrieval_errors=list(state.get("retrieval_errors") or []),
        )
        qa_passed = result.get("qa_passed", True)
        issues = normalize_qa_issues(result.get("qa_issues", []))
        return {
            "qa_passed": qa_passed,
            "qa_issues": issues,
            "new_decision_entries": [
                f"QA check {'passed' if qa_passed else 'found issues'}: {len(issues)} issue(s)."
            ],
        }
    except (ValueError, TypeError, TimeoutError, RuntimeError) as exc:
        label = _exception_label(exc)
        logger.error("run_qa_check failed (fail-closed, {}) : {}", label, exc)
        return {
            "qa_passed": False,
            "qa_issues": [
                {
                    "code": "QA_CHECK_ERROR",
                    "severity": "critical",
                    "message": f"QA check error ({label}): {exc}",
                }
            ],
            "new_errors": [f"qa_check[{label}]: {exc}"],
            "new_decision_entries": [f"QA check failed closed: {exc}"],
        }


def route_after_qa(
    state: SynthesisState,
) -> Literal["generate_report", "attempt_qa_fix", "flag_re_evaluation"]:
    if state.get("qa_passed", True):
        return "generate_report"
    if bool(state.get("synthesis_needs_re_evaluation", False)):
        return "flag_re_evaluation"
    if state.get("qa_fix_attempts", 0) < _MAX_QA_FIX_ATTEMPTS:
        return "attempt_qa_fix"
    return "flag_re_evaluation"


async def attempt_qa_fix(state: SynthesisState) -> dict[str, object]:
    return await _attempt_qa_fix_impl(state)


async def flag_re_evaluation(state: SynthesisState) -> dict[str, object]:
    return await _flag_re_evaluation_impl(state)


def _collect_synthesis_inputs(state: SynthesisState) -> dict[str, object]:
    return collect_synthesis_inputs(state)


async def generate_report_node(state: SynthesisState) -> dict[str, object]:
    try:
        ctx = collect_synthesis_inputs(state)
        report = await report_generator.build_report(**ctx)
        return {
            "report_json": report,
            "report_text": report_generator.build_text_report(report),
            "synthesis_needs_re_evaluation": False,
            "synthesis_retry_retrieval": False,
            "new_decision_entries": ["Final report generated by synthesis sub-agent."],
        }
    except (ValueError, TypeError, TimeoutError, RuntimeError) as exc:
        label = _exception_label(exc)
        logger.error("generate_report failed ({}) : {}", label, exc)
        return {
            "report_json": {"error": str(exc), "error_type": label},
            "report_text": f"Report generation failed ({label}): {exc}",
            "synthesis_needs_re_evaluation": False,
            "synthesis_retry_retrieval": False,
            "new_errors": [f"generate_report[{label}]: {exc}"],
            "new_decision_entries": [f"Report generation failed: {exc}"],
        }


async def finalize_synthesis_output(state: SynthesisState) -> dict[str, object]:
    return {
        "qa_issues": normalize_qa_issues(state.get("qa_issues") or []),
        "qa_passed": bool(state.get("qa_passed", True)),
        "report_json": state.get("report_json"),
        "report_text": state.get("report_text"),
        "synthesis_needs_re_evaluation": bool(state.get("synthesis_needs_re_evaluation", False)),
        "synthesis_retry_retrieval": bool(state.get("synthesis_retry_retrieval", False)),
        "qa_remediation": build_remediation_summary(state),
        "decision_history": list(state.get("new_decision_entries") or []),
        "errors": list(state.get("new_errors") or []),
    }
