from __future__ import annotations

from collections import Counter
from datetime import UTC, datetime
from typing import Any

from config import get_llm
from langchain_core.prompts import ChatPromptTemplate
from loguru import logger
from prompts.synthesis import build_synthesis_prompt
from pydantic import BaseModel, Field
from tools.retry import llm_retry


class ExecutiveSummaryModel(BaseModel):
    executive_summary: str = Field(
        description="A 150-250 word physician-level executive summary of the trial matches."
    )
    patient_summary: str = Field(
        description="A concise 1-sentence demographic and clinical description of the patient"
    )


def _count_tiers(scored_trials: list[dict[str, Any]]) -> tuple[int, int, int]:
    tiers = Counter(t.get("tier") for t in scored_trials)
    return tiers["strong_match"], tiers["possible_match"], tiers["unlikely_match"]


def _describe_patient(patient_profile: dict[str, Any]) -> str:
    conds = patient_profile.get("conditions", [])
    primary = patient_profile.get("primary_condition") or conds[0] if conds else "unknown condition"
    age = patient_profile.get("age", "unknown age")
    sex = patient_profile.get("sex", "")
    return f"{age} year old {sex} patient with {primary}".strip()


def _build_exec_summary_context(
    patient_profile: dict[str, Any],
    scored_trials: list[dict[str, Any]],
    missing_info: list[dict[str, Any]],
) -> dict[str, Any]:
    strong, possible, unlikely = _count_tiers(scored_trials)
    top_trials_summary = "\n".join(
        f"- {t['brief_title']} ({t['trial_id']}): score={t['score']:.2f}, "
        f"meets={t['meets_count']}, fails={t['fails_count']}, uncertain={t['uncertain_count']}"
        for t in scored_trials[:5]
    )
    patient_sum = _describe_patient(patient_profile)
    missing_str = ", ".join(item.get("field", "") for item in missing_info[:3]) or "none identified"
    return {
        "patient_summary": patient_sum,
        "strong_count": strong,
        "possible_count": possible,
        "unlikely_count": unlikely,
        "total": len(scored_trials),
        "top_trials": top_trials_summary or "No trials evaluated",
        "missing_info": missing_str,
    }


@llm_retry
async def _invoke_exec_summary_llm(chain: Any, context: dict[str, Any]) -> dict[str, Any]:
    result = await chain.ainvoke(
        context,
        config={"run_name": "executive_summary", "tags": ["synthesis", "report"]},
    )
    if not isinstance(result, ExecutiveSummaryModel):
        raise ValueError(f"Unexpected report summary result type: {type(result)}")
    return result.model_dump()


async def generate_executive_summary(
    patient_profile: dict[str, Any],
    scored_trials: list[dict[str, Any]],
    missing_info: list[dict[str, Any]],
) -> dict[str, str]:
    context = _build_exec_summary_context(patient_profile, scored_trials, missing_info)
    prompt = ChatPromptTemplate.from_template(build_synthesis_prompt())
    chain = prompt | get_llm().with_structured_output(ExecutiveSummaryModel)

    try:
        result = await _invoke_exec_summary_llm(chain, context)
        return {
            "executive_summary": result["executive_summary"],
            "patient_summary": result["patient_summary"],
        }
    except Exception as exc:
        logger.error("Executive summary generation failed after retries: %s", exc)

    patient_sum = context["patient_summary"]
    return {
        "executive_summary": (
            f"Analysis of {len(scored_trials)} clinical trials for {patient_sum}. "
            f"Found {context['strong_count']} strong, {context['possible_count']} possible, "
            f"and {context['unlikely_count']} unlikely matches."
        ),
        "patient_summary": patient_sum,
    }


def _build_trial_report_entry(
    trial: dict[str, Any], eligibility_verdicts: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    tid = trial.get("trial_id", "")
    enriched = dict(trial)
    enriched["verdict_details"] = eligibility_verdicts.get(tid, {})
    return enriched


_METHODOLOGY_NOTE = (
    "This report was generated by an automated multi-agent system using large language model "
    "reasoning to assess eligibility criteria. All results should be reviewed by a qualified "
    "clinician before making enrollment decisions. Scoring: strong_match (>0.7), "
    "possible_match (0.4-0.7), unlikely_match (<0.4). Hard exclusion failures apply -0.5 penalty each."
)


async def build_report(
    patient_profile: dict[str, Any],
    scored_trials: list[dict[str, Any]],
    missing_info: list[dict[str, Any]],
    eligibility_verdicts: dict[str, dict[str, Any]],
    trials_raw: list[dict[str, Any]],
    search_queries: list[str],
    decision_history: list[str],
    qa_issues: list[str],
) -> dict[str, Any]:
    summary_data = await generate_executive_summary(patient_profile, scored_trials, missing_info)
    enriched_trials = [_build_trial_report_entry(t, eligibility_verdicts) for t in scored_trials]
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "patient_summary": summary_data.get("patient_summary", ""),
        "executive_summary": summary_data.get("executive_summary", ""),
        "total_trials_searched": len(trials_raw),
        "total_trials_evaluated": len(scored_trials),
        "strong_matches": [t for t in enriched_trials if t.get("tier") == "strong_match"],
        "possible_matches": [t for t in enriched_trials if t.get("tier") == "possible_match"],
        "unlikely_matches": [t for t in enriched_trials if t.get("tier") == "unlikely_match"],
        "missing_info": missing_info,
        "qa_issues": qa_issues,
        "methodology_note": _METHODOLOGY_NOTE,
        "search_queries_used": list(dict.fromkeys(search_queries)),
        "decision_history": decision_history,
    }


def _render_trial_entry(t: dict[str, Any]) -> list[str]:
    lines = [
        f"[{t['trial_id']}] {t['brief_title']}",
        f"Score: {t['score']:.2f} | Confidence: {t['confidence']:.2f} | "
        f"Phase: {t.get('phase', 'N/A')} | Status: {t.get('overall_status', 'N/A')}",
        f"Criteria: {t['meets_count']} met / {t['fails_count']} failed / "
        f"{t['uncertain_count']} uncertain",
    ]
    if t.get("key_inclusion_passed"):
        lines.append(f"Key inclusions met: {'; '.join(t['key_inclusion_passed'])}")
    if t.get("key_exclusion_failed"):
        lines.append(f"Key exclusions failed: {'; '.join(t['key_exclusion_failed'])}")
    if t.get("key_uncertain"):
        lines.append(f"Key uncertainties: {'; '.join(t['key_uncertain'])}")
    if t.get("locations_summary"):
        lines.append(f"Locations: {', '.join(t['locations_summary'])}")
    lines.append("")
    return lines


def _render_tier_section(report_json: dict[str, Any], tier: str, label: str) -> list[str]:
    trials = report_json.get(tier, [])
    if not trials:
        return []
    lines = [f"{label} ({len(trials)}):", "-" * 40]
    for t in trials:
        lines.extend(_render_trial_entry(t))
    return lines


def _render_missing_section(missing: list[dict[str, Any]]) -> list[str]:
    if not missing:
        return []
    lines = ["INFORMATION GAPS", "-" * 40]
    for item in missing:
        priority = item.get("priority", "medium").upper()
        lines.append(f"[{priority}] {item.get('field', '')}")
        lines.append(f"{item.get('description', '')}")
        affected = item.get("affected_trial_ids", [])
        if affected:
            lines.append(f"Affects: {', '.join(affected[:5])}")
        lines.append("")
    return lines


def build_text_report(report_json: dict[str, Any]) -> str:
    """Build human-readable text from report JSON."""
    lines: list[str] = [
        "=" * 70,
        "CLINICAL TRIAL MATCHING REPORT",
        f"Generated: {report_json.get('generated_at', 'N/A')}",
        "=" * 70,
        "",
        "PATIENT: " + report_json.get("patient_summary", ""),
        "",
        "EXECUTIVE SUMMARY",
        "-" * 40,
        report_json.get("executive_summary", ""),
        "",
        f"TRIALS SEARCHED: {report_json.get('total_trials_searched', 0)}  "
        f"EVALUATED: {report_json.get('total_trials_evaluated', 0)}",
        "",
    ]

    for tier, label in [
        ("strong_matches", "STRONG MATCHES"),
        ("possible_matches", "POSSIBLE MATCHES"),
        ("unlikely_matches", "UNLIKELY MATCHES"),
    ]:
        lines.extend(_render_tier_section(report_json, tier, label))

    lines.extend(_render_missing_section(report_json.get("missing_info", [])))

    qa_issues = report_json.get("qa_issues", [])
    if qa_issues:
        lines += ["QA ISSUES", "-" * 40] + [f"  - {issue}" for issue in qa_issues] + [""]

    lines += [
        "METHODOLOGY",
        "-" * 40,
        report_json.get("methodology_note", ""),
        "",
    ]

    return "\n".join(lines)
